### ISSUE TITLE
ftscratch3

### ISSUE THREAD

**Issue by tailindu** [LLK/scratch-l10n#108]
How to build a desktop version for ftscratch3? May you be so kind to record a vedio to show the steps details ? So thank you from Asia,china~~

**Comment by apple502j** [comment]
What is "ftscratch3"?

If you want to know how to build Scratch Desktop, check https://github.com/LLK/scratch-desktop

**Comment by tailindu** [comment]
> What is "ftscratch3"?
> 
> If you want to know how to build Scratch Desktop, check https://github.com/LLK/scratch-desktop

”ftscratch3” combined Fischer and scratch3.0, we can progranmme in TXT by scratch.

**Comment by apple502j** [comment]
This is not a repository for ftscratch. Please close the issue.
