### ISSUE TITLE
Add Aragonese and Western Frisian to the languages

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-l10n#150]
We need to add two new languages. Ideally this would be added by August 17 so that it will be in the desktop release beginning of September

- Western Frisian (fy): written as Frysk and it should be after Francais (fr)
- Aragonese (an): written as Aragonés, and it should be after Amharic (am)
- Bengali (bn): written as বাংলা, and it should be after Bahasa Indonesia

**Comment by tracytangtt** [comment]
Confirmed with translators:

Western Frisian is written locally as **Frysk**. And its [ISO639-1 language code](http://www.loc.gov/standards/iso639-2/php/langcodes-keyword.php?SearchTerm=frisian&SearchType=ALL) is **fy**

Aragonese is written locally as **Aragonés**
