### ISSUE TITLE
Part of the Community Guidelines is not in Spanish 

### ISSUE THREAD

**Issue by ScolderCreations** [LLK/scratch-l10n#160]
Currently, segments of the Community Guideline page are not translated into Español. This is probably a major problem because the community guidelines are basically the rules of the website, and not being able to natively read them would cause potential issues.

**Comment by rschamp** [comment]
Thanks for reporting this! The community guidelines were recently updated, and it takes some time for our translators to get to 100% whenever text changes on the site. Rest assured that they will be fully translated in time.
