### ISSUE TITLE
Kazakh and Northern Sotho might have wrong "set volume" block translation

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-l10n#169]
Kazakh's `set volume to (100) %` is translated as `дыбыс күштілігін 1 (100) %`, and Northern Sotho translates it as `bea volume go 1 (100) %`. I suspect the `1` in the translation is from a placeholder translation error. Can anyone confirm the current translation is correct?

**Comment by chrisgarrity** [comment]
Thanks for noticing, I've fixed the translations in Transifex so they should get updated soon.
