### ISSUE TITLE
about translations

### ISSUE THREAD

**Issue by wwj718** [LLK/scratch-l10n#21]
hi @chrisgarrity ,

I noticed that you submitted the pr: [Update translations from transifex.](https://github.com/LLK/scratch-l10n/commit/f9bb155a230a8c792862fac2c2ff1327a755e90a)

I want to know when it will be updated to scratch-gui/develop

Thanks a lot！

**Comment by chrisgarrity** [comment]
Soon, there are some other things that need to happen first.

**Comment by wwj718** [comment]
Thank you for your reply 😄
