### ISSUE TITLE
Remove wwwLocales

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-l10n#58]
Now that www and gui are in sync for languages, we should remove `wwwLocales`.
It may have originally been used for the project metadata schema:
```
projectSchema.properties.language.enum =
    Object.keys(require('scratch-l10n').default);
```

**Comment by thisandagain** [comment]
@chrisgarrity Is it fair to assign this to you for clean-up in January?

**Comment by chrisgarrity** [comment]
@thisandagain yup, it's mostly checking that it's not in use anywhere.
