### ISSUE TITLE
Dutch translations

### ISSUE THREAD

**Issue by CoderDojoBaarn** [LLK/scratch-l10n#8]
We really would like to share the scratch 3.0 gui with our youngsters but is simply not possible due to lack of dutch translations.
We can help out with the translations but could not find this project yet on transifex, could we in the meantime create a PR for this?

**Comment by thisandagain** [comment]
Hi @CoderDojoBaarn,
Thanks for your interest! We don't have translations quite ready yet, but we would love some help once we are ready! :-D
