### ISSUE TITLE
Add Georgian

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-l10n#88]
Georgian was completed on July 21 (before the deadline I set of July 23), but I missed their message until this morning.

**Comment by chrisgarrity** [comment]
![Screen Shot 2020-02-28 at 2 33 11 PM](https://user-images.githubusercontent.com/399209/75581684-fe0a2400-5a37-11ea-8c27-c4f325b623cb.png)
![Screen Shot 2020-02-28 at 2 33 47 PM](https://user-images.githubusercontent.com/399209/75581691-019dab00-5a38-11ea-9337-390803a23f0a.png)
![Screen Shot 2020-02-28 at 2 33 57 PM](https://user-images.githubusercontent.com/399209/75581697-04000500-5a38-11ea-9d09-8cd908e35efe.png)
I just need the images uploaded for the wiki

**Comment by benjiwheeler** [comment]
> I just need the images uploaded for the wiki

Is that something I could help with?
