### ISSUE TITLE
Broken link to coding cards projects in wiki

### ISSUE THREAD

**Issue by MMSequeira** [LLK/scratch-l10n#91]
The [link to the zip file of the projects used in the Coding Cards](https://drive.google.com/open?id=16RtjMZrLNfncKPC8WWfnhmDskApy2Dst) in the [Coding Card Project section of the wiki page Translating Scratch Coding Cards](https://github.com/LLK/scratch-l10n/wiki/Translating-Scratch-Coding-Cards#coding-card-projects) seems to be broken.

**Comment by tarmelop** [comment]
The link seems to be still broken. @chrisgarrity any update on this issue?

**Comment by chrisgarrity** [comment]
@tarmelop just fixed it.
